import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import { getSession } from '@/auth'
import { QueryProvider } from '@/components/providers/query-provider'
import { SessionProvider } from '@/components/providers/session-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'

const font = Montserrat({
	subsets: ['latin', 'vietnamese']
})

export const metadata: Metadata = {
	title: 'FIMI',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getSession()

	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body className={cn(font.className, 'antialiased')}>
				<SessionProvider session={session}>
					<ThemeProvider>
						<QueryProvider>{children}</QueryProvider>
						<Toaster />
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	)
}
